### ISSUE TITLE
Feedback del formulario

### ISSUE THREAD

**Issue by cristianperezshiba** [UB-ES-19/F1-Idealista#3]
Que en el formulario de registro (en la página de registro) se vean reflejados las acciones que el usuario toma (e.g. mensaje de error si escribe el mail equivocado)

*Nota: únicamente interfaz de usuario, no la parte de servidor*

**Comment by kanales** [comment]
Por motivos de alta correspondencia entre este issue y #2, se completará en la rama 2

**Comment by kanales** [comment]
Para usarse desde backend, simplemente hay que añadir `.is-invalid` al componente que ha dado una entrada invalida.
