### ISSUE TITLE
Diseñar el modelo

### ISSUE THREAD

**Issue by cristianperezshiba** [UB-ES-19/F1-Idealista#5]
Implementar la tabla de usuarios y los métodos que sean necesarios para interactuar con él.

**Comment by aadevafi7** [comment]
Al realizar la migracion con django establece unas tablas por defecto, las cuales una es "auth_user" que es donde se almacenan los usuarios que se registran en la aplicación.

**Comment by aadevafi7** [comment]
Para crear la base de datos solo es necesario realizar en el terminal:

$ python manage.py makemigrations idealista_app
$ python manage.py migrate

El cual entre las tablas que se crean de django esta la tabla "auth_user" que contiene los campos:
- username
- password
- first_name

Que son los necesarios para el registro.
